### PR TITLE
fix: pass the exit status to parent

### PR DESCRIPTION
**Pull request by GitaiQAQ**

### CODE REVIEW

**Comment by kt3k** [comment]
What use case does this fix?

If I try the below Node.js code, then the exit code was 1 instead of 42:

```js
process.exitCode = 42
throw new Error();
```

I think this doesn't make difference when the exit code is non zero.

**Comment by wojpawlik** [comment]
https://github.com/denoland/deno/issues/17065

**Review by wojpawlik — APPROVED** [review]
`p.error` is set only when process times out or fails to spawn. For other cases, forwarding exit code is necessary.

Note that this doesn't handle `p.signal`. #15 might've been a mistake...

image


Readme should probably recommend `npm rebuild deno-bin` if installing with `--ignore-scripts`... shall I PR?

**Comment by kt3k** [comment]
Fair enough. Let's land this

@wojpawlik BTW are you against #16? What is your concern? With #16 we can directly install deno executable at node_modules/.bin/deno without executing any script.

**Comment by wojpawlik** [comment]
It just _feels_ complex. But the current setup isn't straightforward either: https://github.com/npm/cli/issues/2670#issuecomment-778643530. If only (p)npm supported https://yarnpkg.com/configuration/manifest#dependenciesMeta.built...

**Comment by wojpawlik** [comment]
I'd also allow to ditch both third-party dependencies. It might be a good idea after all, it's just hard to tell without any guidelines. 

Generating `package.json`s would probably be the hardest part.

**Pull request merged**
